AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: Internet Gateway configuration infra
Parameters:
  EnvironmentName:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  AppName:
    Type: String
  Name:
    Type: String
    Description: An environment name that will be prefixed to resource names

  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the security groups should be deployed to

  PublicSubnets:
    Type: CommaDelimitedList
    Description: List of names of network subnets

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Name}-ig

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCID
  
  'Fn::ForEach::ElasticIPs':
    - SubnetName
    - !Ref PublicSubnets
    - 'ElasticIP${SubnetName}':
        Type: AWS::EC2::EIP
        DependsOn: InternetGatewayAttachment
        Properties:
          Domain: vpc
          Tags:
            - Key: Name
              Value: !Sub ${Name}-eip-${SubnetName}
    
  'Fn::ForEach::NatGateways':
    - SubnetName
    - !Ref PublicSubnets
    - 'Fn::ForEach::GetAttLoop':
      - Property
      - [AllocationId]
      - 'NatGateway${SubnetName}':
          Type: AWS::EC2::NatGateway
          Properties:
            AllocationId: !GetAtt
              - !Sub 'ElasticIP${SubnetName}'
              - !Ref Property
            SubnetId: !Sub '{{resolve:ssm:/config/infra/${EnvironmentName}/${AppName}/public_subnet/${SubnetName}}}'
            Tags:
              - Key: Name
                Value: !Sub ${Name}-nat-${SubnetName}
  
  'Fn::ForEach::NatGatewayOutputSSM':
    - SubnetName
    - !Ref PublicSubnets
    - 'Fn::ForEach::GetAttLoop':
      - Property
      - [NatGatewayId]
      - 'SSM${Property}${SubnetName}':
          Type: AWS::SSM::Parameter
          Properties:
            Name: !Sub "/config/infra/${EnvironmentName}/${AppName}/nat_gateway/${SubnetName}"
            Type: String
            Value: !GetAtt 
              - !Sub 'NatGateway${SubnetName}'
              - !Ref Property

Outputs:
  StackName:
    Value: !Sub '${AWS::StackName}'

  InternetGateway:
    Value: !Ref InternetGateway

