AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: Internet Gateway configuration infra
Parameters:
  EnvironmentName:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  AppName:
    Type: String
  Name:
    Type: String
    Description: An environment name that will be prefixed to resource names

  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the security groups should be deployed to

  PublicSubnets:
    Type: CommaDelimitedList
    Description: List of names of network subnets

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Name}-ig

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCID
  
  EgressOnlyInternetGateway: 
    Type: AWS::EC2::EgressOnlyInternetGateway
    Properties: 
        VpcId: !Ref VPCID

Outputs:
  StackName:
    Value: !Sub '${AWS::StackName}'

  InternetGateway:
    Value: !Ref InternetGateway
  
  EOInternetGateway:
    Value: !Ref EgressOnlyInternetGateway
